[feat] Implement OP_DATA_X opcodes, OP_DATA_7 - OP_DATA_75
keep-starknet-strange/shinigami pull request #119
Opened 2024-08-08 09:17 UTC by Shoetan

- [x] issue #https://github.com/keep-starknet-strange/shinigami/issues/116
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

## Implement `OP_DATA_X` opcodes from `op_data_7` to `op_data_75`

2024-08-08 15:43 UTC, b-j-roberts requested changes
Looks good, just one small thing.

Also, please run `scarb fmt` to fix CI checks.

2024-08-08 15:43 UTC, b-j-roberts commented on src/opcodes/tests/test_constants.cairo
> +    test_op_data(7);
Could you change this `test_op_data_all` function to use a loop instead of repeating this for each number?

2024-08-08 16:19 UTC, Shoetan commented
Alright got it. 🚀

2024-08-08 16:21 UTC, Shoetan commented
Alright got it. 🚀

2024-08-08 17:47 UTC, Shoetan commented
@b-j-roberts  refactored as requested.

2024-08-08 18:24 UTC, Shoetan reviewed
Refactored using while loop and running `scarb fmt` for linting.

2024-08-09 16:29 UTC, b-j-roberts approved these changes
Nice work! Thanks for getting these setup

2024-08-09 16:30 UTC, merged