coinbase transactions
keep-starknet-strange/shinigami pull request #181
Opened 2024-08-28 04:46 UTC by harsh-ps-2003

- [x] issue #173 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

Adds support for Coinbase Transactions (Basic and BIP34) with tests.

2024-08-28 12:18 UTC, harsh-ps-2003 commented
@b-j-roberts can you take a look?

2024-08-29 01:37 UTC, b-j-roberts requested changes
Nice work so far!

I was thinking we could create a validate type function that takes a transaction argument and verifies it is a valid coinbase transaction.

I think the coinbase logic from this file should be a good guide on that : https://github.com/btcsuite/btcd/blob/2b53ed198955ac40fe5b3ce4a854e9f5bfa68258/blockchain/validate.go#L28

Lmk if you are able to do this. Thanks

2024-08-29 01:37 UTC, b-j-roberts commented on src/test_coinbase.cairo
> +use shinigami::transaction::TransactionInput;
Can you combine these into something like `use shinigami::transaction::{TransactionTrait, Transaction, ...}`?

2024-08-29 01:37 UTC, b-j-roberts commented on src/test_coinbase.cairo
Could you move this file into `src/tests/`?

2024-08-30 00:12 UTC, b-j-roberts requested changes
Would be nice to have a set of tests that create and validate various coinbase transactions from mainnet blocks.
Some that would be interesting to add would be the block 0 coinbase transaction, block 1 coinbase transaction, block 227,836 coinbase transaction ( 1st bip34 coinbase ), 481,824 coinbase transaction ( last before segwit ).

2024-08-30 00:12 UTC, b-j-roberts commented on src/transaction.cairo
> +    fn validate_coinbase(tx: Transaction) -> bool {
Can you make this function return a `Result<(),felt252>`, and add some errors to `src/errors.cairo` for invalid coinbase?

2024-08-30 08:40 UTC, harsh-ps-2003 commented
@b-j-roberts in case of testing using coinbase transactions from main net, I have only taken [one latest output instead of many](https://btcscan.org/block/000000000000000000cbeff0b533f8e1189cf09dfbebf57a8ebe349362811b80).

2024-08-30 19:21 UTC, harsh-ps-2003 commented
@b-j-roberts in case of testing using coinbase transactions from main net, I have only taken [one latest output instead of many](https://btcscan.org/block/000000000000000000cbeff0b533f8e1189cf09dfbebf57a8ebe349362811b80).

2024-09-04 03:04 UTC, b-j-roberts approved these changes
Thank you!
I added some extra features on top, like raw transaction decoding, to improve the tests for Coinbase a bit.

2024-09-04 03:04 UTC, merged