add op_checksigadd
keep-starknet-strange/shinigami pull request #202
Opened 2024-09-05 21:50 UTC by harsh-ps-2003

- [ ] issue #
- [ ] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

Adds opcode checksigadd!
Reference - https://en.bitcoin.it/wiki/BIP_0342

2024-09-05 22:05 UTC, harsh-ps-2003 commented
@b-j-roberts can you take a look why am I getting i64 overflow :(

2024-09-06 14:51 UTC, j1mbo64 commented on src/opcodes/tests/test_crypto.cairo
> +    let script_pubkey = "OP_1 OP_SWAP OP_SWAP OP_CHECKSIGADD";
You do OP_SWAP twice, so the stack is again [SIG, PK, N] and after you try to make a number with the public key which result in an overflow. Can you try to remove one OP_SWAP ?

2024-09-10 02:28 UTC, j1mbo64 requested changes

2024-09-10 02:28 UTC, j1mbo64 commented on src/opcodes/crypto.cairo
> +    if n > 0x7FFFFFFF || n < -0x80000000 {
This test is already done at line 245 in `pop_int`

2024-09-10 02:28 UTC, j1mbo64 commented on src/opcodes/crypto.cairo
> +    if pk_bytes.len() == 32 {
I think this test can be removed, `verify` result as an error if the key is not in the good format. You're also pushing 33 bytes public key so this test is always false

2024-09-10 02:28 UTC, j1mbo64 commented on src/opcodes/crypto.cairo
> +            is_valid = true;
Your test `test_checksigadd_valid` pass because you execute this

2024-09-10 02:28 UTC, j1mbo64 commented on src/opcodes/crypto.cairo
> +        return Result::Err('EmptyPublicKey');
You should create an error in `Errors.cairo`

2024-09-10 05:58 UTC, closed without merging

2024-09-10 05:59 UTC, harsh-ps-2003 commented
@j1mbo64 sorry! I dont have the bandwidth to fix the tests! Thank you for the review! Maybe you can reopen the PR and take up the work further if you want!