add p2wpkh tests
keep-starknet-strange/shinigami pull request #261
Opened 2024-10-17 07:31 UTC by JoE11-y

- [x] issue #249 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

2024-10-17 14:02 UTC, b-j-roberts requested changes

2024-10-17 14:02 UTC, b-j-roberts commented on packages/tests/src/tests/test_p2wpkh.cairo
> +        "0x020000000001016972546966be990440a0665b73d0f4c3c942592d1f64d1033717aaa3e2c2ec913300000000ffffffff024087100000000000160014841b80d2cc75f5345c482af96294d04fdd66b2b760e31600000000001600142e8734
I think this issue should be fixed on all the tests

2024-10-17 18:24 UTC, JoE11-y commented on packages/tests/src/tests/test_p2wpkh.cairo
> +        "0x020000000001016972546966be990440a0665b73d0f4c3c942592d1f64d1033717aaa3e2c2ec913300000000ffffffff024087100000000000160014841b80d2cc75f5345c482af96294d04fdd66b2b760e31600000000001600142e8734
I've fixed the issue with the tests.

2024-10-20 01:12 UTC, b-j-roberts approved these changes
Nice work, thank you!

2024-10-20 01:12 UTC, merged