feat: op_MAX implementation
keep-starknet-strange/shinigami pull request #27
Opened 2024-07-25 13:39 UTC by lomasson

- [x] issue #18 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

2024-07-25 15:13 UTC, b-j-roberts requested changes
Thank you!

2024-07-25 15:13 UTC, b-j-roberts commented on src/opcodes/opcodes.cairo
> +        if engine.dstack.len() < 2 {
I think this check can be removed, since the failure will be propagated form the `pop_int` operation in the future.

2024-07-25 15:13 UTC, b-j-roberts commented on src/opcodes/tests/test_opcodes.cairo
> +fn test_op_max_with_one_element() {
This test can be removed until we have a proper error propagation.

2024-07-25 16:21 UTC, lomasson commented
I have fix that. @b-j-roberts

2024-07-26 15:01 UTC, merged

2024-07-26 15:01 UTC, b-j-roberts commented
Nice work, thank you!