feat:implement OP_RESERVED opcode
keep-starknet-strange/shinigami pull request #49
Opened 2024-07-29 07:01 UTC by Jemiiah

- [ ] issue #4 
- [ ] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

implemented code for using the opcodeReserved reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L774)

2024-07-29 13:24 UTC, Jemiiah commented
@b-j-roberts please kindly review this issue

2024-07-30 20:28 UTC, b-j-roberts requested changes

2024-07-30 20:28 UTC, b-j-roberts commented on src/opcodes/opcodes.cairo
> +        format!("attempt to execute reserved opcode");
I believe this should be using `panic!` to throw an error for now, this is just formatting a string.

2024-07-30 20:28 UTC, b-j-roberts commented on src/opcodes/tests/test_opcodes.cairo
> +#[test]
Then in this test, we will want to check that an error was thrown using the `should_panic` declaration: https://book.cairo-lang.org/ch10-01-how-to-write-tests.html?highlight=expect#checking-for-panics-with-should_panic

2024-08-01 09:09 UTC, closed without merging